version: "3"
services:
  node:
    user: node
    image: "podscripts-react:latest"
    working_dir: /home/node/code/podscripts_site_react 
    environment:
      - NODE_ENV=production
      - NPM_CONFIG_PREFIX=/home/node/.npm-global
      - PATH=$PATH:/home/node/.npm-global/bin
    expose:
      - "8001"
    platform: linux/amd64
    ports:
      - "8001:8001"  
    command: >
      sh -c "npm install -g serve &&
             serve -s build -l 8001"
  podscripts-nginx:
    image: nginx
    container_name: podscripts-nginx
    ports:
      - "9280:80"
    volumes:
      - /volume2/rss_to_whisper:/usr/share/nginx/html:ro